exclude: "docs|node_modules|migrations|.git|.tox"
default_stages: [commit]
fail_fast: true
default_language_version:
  python: python3.11

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.8.0
    hooks:
      - id: pyupgrade
        args: [--py311-plus]

  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black

  # - repo: https://github.com/pycqa/flake8
  #   rev: 6.0.0
  #   hooks:
  #     - id: flake8
  #       args: ["--config=setup.cfg"]
  #       additional_dependencies:
  #         - flake8-isort
  #         - flake8-no-pep420==2.0.0
  #         - flake8-print
  #         - flake8-breakpoint

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.0.275
    hooks:
      - id: ruff

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
