# SPDX-License-Identifier: Apache-2.0
"""Public model re-exports.

Consumers import from ``pynteracta.models``, not from ``generated/`` directly.
Generated models remain accessible via ``pynteracta.models.generated.external_v2``
as the documented escape hatch.
"""

from pynteracta.models.facade import (
    AttachmentDetail,
    AttachmentVisibility,
    Catalog,
    CatalogEntry,
    CatalogEntryList,
    CatalogList,
    CheckVisibilityRequestDTO,
    Community,
    CommunityDetail,
    CommunityList,
    CreateAccessTokenByServiceAccountRequestDTO,
    CurrentUserResponse,
    FieldType,
    GetPostDefinitionCatalogsRequestDTO,
    GlobalPostStream,
    GoogleOAuth2AccessTokenResponse,
    ListCommunitiesRequestDTO,
    ListCommunityPostsFilteredRequestDTO,
    ListCommunityPostsRequestDTO,
    ListPostCommentsRequestDTO,
    ListPostDefinitionCatalogEntriesRequestDTO,
    ListPostHistoryEventsRequestDTO,
    ListSystemUsersRequestDTO,
    Post,
    PostAttachment,
    PostAttachmentList,
    PostCapabilities,
    PostCommentList,
    PostDefinition,
    PostDefinitionMap,
    PostFieldDefinition,
    PostHistoryEventList,
    PostList,
    ServiceAccountTokenResponse,
    SubTask,
    SystemUserList,
    Task,
    TaskCapabilities,
    TaskReminder,
    UserForEdit,
    UserProfile,
    VisibilityResult,
)

__all__ = [
    "AttachmentDetail",
    "AttachmentVisibility",
    "Catalog",
    "CatalogEntry",
    "CatalogEntryList",
    "CatalogList",
    "CheckVisibilityRequestDTO",
    "Community",
    "CommunityDetail",
    "CommunityList",
    "CreateAccessTokenByServiceAccountRequestDTO",
    "CurrentUserResponse",
    "FieldType",
    "GetPostDefinitionCatalogsRequestDTO",
    "GlobalPostStream",
    "GoogleOAuth2AccessTokenResponse",
    "ListCommunitiesRequestDTO",
    "ListCommunityPostsFilteredRequestDTO",
    "ListCommunityPostsRequestDTO",
    "ListPostCommentsRequestDTO",
    "ListPostDefinitionCatalogEntriesRequestDTO",
    "ListPostHistoryEventsRequestDTO",
    "ListSystemUsersRequestDTO",
    "Post",
    "PostAttachment",
    "PostAttachmentList",
    "PostCapabilities",
    "PostCommentList",
    "PostDefinition",
    "PostDefinitionMap",
    "PostFieldDefinition",
    "PostHistoryEventList",
    "PostList",
    "ServiceAccountTokenResponse",
    "SubTask",
    "SystemUserList",
    "Task",
    "TaskCapabilities",
    "TaskReminder",
    "UserForEdit",
    "UserProfile",
    "VisibilityResult",
]
